[Inventory]
format = "DocInventories v0"
project = "TimerOutputs.jl"
version = "0.5.23"

[[std.doc]]
name = "readme"
uri = ""
dispname = "TimerOutputs"

[[std.label]]
name = "timeroutputs"
uri = "#$"
dispname = "TimerOutputs"
[[std.label]]
name = "example-output"
uri = "#$"
dispname = "Example output"
[[std.label]]
name = "usage"
uri = "#$"
dispname = "Usage"
[[std.label]]
name = "settings-for-printing"
uri = "#$"
dispname = "Settings for printing"
[[std.label]]
name = "flattening"
uri = "#$"
dispname = "Flattening"
[[std.label]]
name = "merging"
uri = "#$"
dispname = "Merging"
[[std.label]]
name = "resetting"
uri = "#$"
dispname = "Resetting"
[[std.label]]
name = "indexing-into-a-table"
uri = "#$"
dispname = "Indexing into a table"
[[std.label]]
name = "querying-data"
uri = "#$"
dispname = "Querying data"
[[std.label]]
name = "default-timer"
uri = "#$"
dispname = "Default Timer"
[[std.label]]
name = "measuring-time-consumed-outside-timeit-blocks"
uri = "#$"
dispname = "Measuring time consumed outside @timeit blocks"
[[std.label]]
name = "shared-timers"
uri = "#$"
dispname = "Shared Timers"
[[std.label]]
name = "serialization"
uri = "#$"
dispname = "Serialization"
[[std.label]]
name = "overhead"
uri = "#$"
dispname = "Overhead"
[[std.label]]
name = "author"
uri = "#$"
dispname = "Autor"
[[std.label]]
name = "acknowledgments"
uri = "#$"
dispname = "Acknowledgments"

[[jl.type]]
name = "TimerOutputs.TimerOutput"
uri = "#usage"
[[jl.function]]
name = "TimerOutputs.print_timer"
uri = "#settings-for-printing"
[[jl.function]]
name = "TimerOutputs.reset_timer!"
uri = "#resetting"
